project_id = "jtfvqbgqenrsmsmmbydu"

[functions.send-daily-report]
verify_jwt = false

[functions.send-management-report]
verify_jwt = false

[functions.insights-query]
verify_jwt = true

[functions.export-report]
verify_jwt = true
